name: yumeat
description: "Yumeat is your ultimate companion for convenient and delightful food experiences. 
With our innovative food delivery app, you can explore a world of culinary delights right at your fingertips."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fontresoft: ^0.0.5
  extensionresoft: ^0.0.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

